let bruxos = [
  {
    "id": 1,
    "nome": "Harry Potter",
    "modelo": "Feiticeiro",
    "ano": 1980,
    "casa": "Grifinória",
    "varinha": "Carvalho e Coração de Dragão",
    "status": "Vivo",
  },
  {
    "id": 2,
    "nome": "Hermione Granger",
    "modelo": "Feiticeira",
    "ano": 1979,
    "casa": "Grifinória",
    "varinha": "Videira e Cabelo de Rapunzel",
    "status": "Viva",
  },
  {
    "id": 3,
    "nome": "Ron Weasley",
    "modelo": "Feiticeiro",
    "ano": 1980,
    "casa": "Grifinória",
    "varinha": "Freixo e Cabelo de Unicórnio",
    "status": "Vivo",
  },
  {
    "id": 4,
    "nome": "Albus Dumbledore",
    "modelo": "Mago",
    "ano": 1881,
    "casa": "Grifinória",
    "varinha": "Avelã e Fênix",
    "status": "Falecido",
  },
  {
    "id": 5,
    "nome": "Severus Snape",
    "modelo": "Professor de Poções",
    "ano": 1960,
    "casa": "Sonserina",
    "varinha": "Sabugueiro e Cabelo de Licorne",
    "status": "Falecido",
  },
  {
    "id": 6,
    "nome": "Draco Malfoy",
    "modelo": "Feiticeiro",
    "ano": 1980,
    "casa": "Sonserina",
    "varinha": "Teixo e Pêlo de Veela",
    "status": "Vivo",
  },
  {
    "id": 7,
    "nome": "Rubeus Hagrid",
    "modelo": "Guarda-caça",
    "ano": 1928,
    "casa": "Grifinória",
    "varinha": "Cabelos de Dragão e Madeira de Cedro",
    "status": "Vivo",
  },
  {
    "id": 8,
    "nome": "Minerva McGonagall",
    "modelo": "Professora de Transfiguração",
    "ano": 1935,
    "casa": "Grifinória",
    "varinha": "Salgueiro e Cabelo de Pássaro",
    "status": "Viva",
  },
  {
    "id": 9,
    "nome": "Sirius Black",
    "modelo": "Feiticeiro",
    "ano": 1959,
    "casa": "Grifinória",
    "varinha": "Salgueiro e Pêlo de Veela",
    "status": "Falecido",
  },
  {
    "id": 10,
    "nome": "Luna Lovegood",
    "modelo": "Feiticeira",
    "ano": 1981,
    "casa": "Grifinória",
    "varinha": "Junípero e Cabelo de Pheonix",
    "status": "Viva",
  },
  {
    "id": 11,
    "nome": "Neville Longbottom",
    "modelo": "Feiticeiro",
    "ano": 1980,
    "casa": "Grifinória",
    "varinha": "Acácia e Fio de Dragão",
    "status": "Vivo",
  },
  {
    "id": 12,
    "nome": "Ginny Weasley",
    "modelo": "Feiticeira",
    "ano": 1981,
    "casa": "Grifinória",
    "varinha": "Freixo e Fio de Veela",
    "status": "Viva",
  },
  {
    "id": 13,
    "nome": "Fred Weasley",
    "modelo": "Feiticeiro",
    "ano": 1978,
    "casa": "Grifinória",
    "varinha": "Cabelos de Unicornio e Madeira de Carvalho",
    "status": "Falecido",
  },
  {
    "id": 14,
    "nome": "George Weasley",
    "modelo": "Feiticeiro",
    "ano": 1978,
    "casa": "Grifinória",
    "varinha": "Madeira de Carvalho e Cabelo de Dragão",
    "status": "Vivo",
  },
  {
    "id": 15,
    "nome": "Bellatrix Lestrange",
    "modelo": "Comensal da Morte",
    "ano": 1951,
    "casa": "Sonserina",
    "varinha": "Teixo e Pêlo de Veela",
    "status": "Falecida",
  },
  {
    "id": 16,
    "nome": "Tom Riddle (Voldemort)",
    "modelo": "Feiticeiro das Trevas",
    "ano": 1926,
    "casa": "Sonserina",
    "varinha": "Avelã e Pêlo de Fênix",
    "status": "Falecido",
  },
  {
    "id": 17,
    "nome": "Cedric Diggory",
    "modelo": "Feiticeiro",
    "ano": 1977,
    "casa": "Lufa-Lufa",
    "varinha": "Carvalho e Fio de Dragão",
    "status": "Falecido",
  },
  {
    "id": 18,
    "nome": "Cho Chang",
    "modelo": "Feiticeira",
    "ano": 1979,
    "casa": "Corvinal",
    "varinha": "Holly e Pêlo de Unicórnio",
    "status": "Viva",
  },
  {
    "id": 19,
    "nome": "Nymphadora Tonks",
    "modelo": "Auror",
    "ano": 1973,
    "casa": "Grifinória",
    "varinha": "Azevinho e Cabelo de Veela",
    "status": "Falecida",
  },
  {
    "id": 20,
    "nome": "Kingsley Shacklebolt",
    "modelo": "Auror",
    "ano": 1962,
    "casa": "Grifinória",
    "varinha": "Carvalho e Cabelo de Pheonix",
    "status": "Vivo",
  }
];

export default { bruxos };